### ISSUE TITLE
Question about proj_mat

### ISSUE THREAD

**Issue by Gilgamesh666666** [phongnhhn92/RGBDNet#4]
Hi,

Thank you for your reply for my last question! I am reading the code recently and I am a little confused about the project matrix:
`proj_mats += [proj_mat_ls @ ref_proj_inv]`
 `proj_mats_ref2inputs += [ref_proj @ torch.inverse(proj_mat_ls)]` 
Why `proj_mats_ref2inputs += [ref_proj @ torch.inverse(proj_mat_ls)]` instead of `proj_mats_ref2inputs += [proj_mat_ls @ ref_proj_inv]`? 
Because I think the projection equation is: 
`ref_depth*ref_pixel = intrinsics*ref_pose*threeD_point`  
`src_depth*src_pixel = intrinsics*src_pose*threeD_point` 
so it is:`(ref_depth/src_depth)*src_proj*inv(ref_proj)*ref_pixel = src_pixel`. Sorry for my stupid question, I shall be very appreciate if you can give me some hint about where I am wrong. Thank you!

**Comment by phongnhhn92** [comment]
Hi @Gilgamesh666666, I used proj_mats_ref2inputs to store the projection matrix from the novel view to the input view. This one is used for the temporal consistent loss. From the generated novel view, I would want to make sure that the generated pixels are consistent across input views. 

Since we start from the novel view (ref_proj) to the input view (proj_mat_ls), we simply perform a matrix multiplication between those projection matrices. Hence we need to take the inverse of the proj_mat_ls. Does it answer your question ?
